---
- name: Allow HTTPS - Grafana
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Allow HTTP - HA-Proxy
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Allow Port 9100 - Node-Exporter
  firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled