---
- name: Create a directory for Grafana installation
  file:
    name: "{{ grafana_location }}"
    state: directory

- name: Download and extract Grafana
  unarchive:
    src: "{{ grafana_dl }}"
    dest: "{{ grafana_location }}"
    extra_opts: "--strip-components=1"
    remote_src: yes

- name: Create a directory for SSL certificates
  file:
    name: "{{ ssl_path }}"
    state: directory 

- name: Create a SSL certificate for Grafana
  shell: openssl req -newkey rsa:2048 -nodes -keyout "{{ ssl_path }}"/"{{ key_name }}" -x509 -days 365 -out "{{ ssl_path }}"/"{{ cert_name }}" -subj "{{ ssl_subj }}"
 
- name: Enable HTTPS for Grafana
  template:
    src: "{{ grafana_config }}"
    dest: "{{ grafana_config_dest }}"

- name: Service creation for "grafana"
  template:
    src: "{{ grafana_service_template }}"
    dest: "{{ grafana_service_dest }}"
  notify: "enable and start Grafana"