---
# tasks file

- name: Download and extract grafana to "/opt"
  unarchive:
    src: "{{ grafana_dl }}"
    dest: "{{ dl }}"
    remote_src: yes

#- name: Service creation for Grafana
#  command: mv /opt/graf* "{{ grafana }}"
#  template:
#    src: "{{ grafana-service }}"
#    dest: "{{ grafana-service-dest }}"
  
#- name: Configuration changes for Grafana
#  template:
#    src: "{{ grafana-service }}"
#    dest: "{{ grafana-service-dest }}"
#  notify: enable grafana

- name: Download and extract prometheus to "/opt"
  unarchive:
    src: "{{ prometheus_dl }}"
    dest: "{{ dl }}"
    remote_src: yes
    
#- name: Service creation for Prometheus
#  command: mv /opt/prom "{{ prometheus }}"
#  template:
#    src: "{{ prometheus-service }}"
#    dest: "{{ prometheus-service-dest }}" 
#  notify: enable prometheus  

- name: Download and extract nodexporter to "/opt"
  unarchive:
    src: "{{ node_exporter_dl }}"
    dest: "{{ dl }}"
    remote_src: yes

#- name: Service creation for Node-Exporter
#  command: mv /opt/node* "{{ node-exporter }}"
#  template:
#    src: "{{ node-exporter-service }}"
#    dest: "{{ node-exporter-dest }}"
#  notify: enable node-exporter

- name: Download and extract haproxy to "/opt"
  unarchive:
    src: "{{ haproxy_dl }}"
    dest: "{{ dl }}"
    remote_src: yes
    
#- name: Build HA-Proxy
#  command: 

    
#- name: Redirect HA-Proxy Port:80 to Grafana:443
  
#- name: Service creation for HA-Proxy
#  command: mv /opt/hapr* "{{ ha-proxy }}" 
#  template:
#    src: "{{ haproxy-service }}"
#    dest: "{{ haproxy-service-dest }}"
#  notify: enable haproxy