---
- import_tasks: grafana.yaml
  tags:
    - grafana

- import_tasks: node_exporter.yaml
  tags:
    - node_exporter

- import_tasks: haproxy.yaml
  tags:
    - haproxy

- import_tasks: firewall_rules.yaml
  tags:
    - firewall
    