---
####################################################
- name: Create a directory for Grafana installation
  file:
    name: "{{ grafana_location }}"
    state: directory

- name: Download and extract Grafana
  unarchive:
    src: "{{ grafana_dl }}"
    dest: "{{ grafana_location }}"
    extra_opts: "--strip-components=1"
    remote_src: yes

- name: Create a directory for SSL certificates
  file:
    name: "{{ ssl_path }}"
    state: directory 

- name: Create a SSL certificate for Grafana
  shell: openssl req -newkey rsa:2048 -nodes -keyout "{{ ssl_path }}"/"{{ key_name }}" -x509 -days 365 -out "{{ ssl_path }}"/"{{ cert_name }}" -subj "{{ ssl_subj }}"
 
- name: Enable HTTPS for Grafana
  template:
    src: "{{ grafana_config }}"
    dest: "{{ grafana_config_dest }}"

- name: Service creation for "grafana"
  template:
    src: "{{ grafana_service_template }}"
    dest: "{{ grafana_service_dest }}"
  notify: "enable and start Grafana"
  
##########################################################
- name: Create a directory for node-exporter installation
  file:
    name: "{{ node_exporter_location }}"
    state: directory

- name: Download and extract node-exporter
  unarchive:
    src: "{{node_exporter_dl}}"
    dest: "{{ node_exporter_location }}"
    extra_opts: "--strip-components=1"
    remote_src: yes

- name: Service creation for "node-exporter"
  template:
    src: "{{ node_exporter_service_template }}"
    dest: "{{ node_exporter_service_dest }}"
  notify: "enable and start node-exporter"

#############################################################

- name: Download and extract HA-Proxy
  unarchive:
    src: "{{haproxy_dl}}"
    dest: /tmp
    remote_src: yes

- name: Create a directory for HA-Proxy installation
  file:
    state: directory
    name: "{{ haproxy_location }}"
    
- name: Install required tools to build HA-Proxy
  yum:
    name: 
      - gcc 
      - openssl-devel 
      - pcre-devel 
      - systemd-devel
    state: latest

- name: Build and install HA-Proxy
  shell: cd /tmp/haproxy* && make "{{ make_args }}" && make install PREFIX="{{ haproxy_location }}"

- name: Create HA-Proxy configuration file with Port redirect (80 to 443)  
  template:
    src: "{{ haproxy_config }}"
    dest: "{{ haproxy_config_dest }}"
    
- name: Service creation for "haproxy"
  template:
    src: "{{ haproxy_service_template }}"
    dest: "{{ haproxy_service_dest }}"
  notify: "enable and start haproxy"
###############################################################