---
# tasks file

- name: Download and extract Grafana to /opt
  unarchive:
    src: https://dl.grafana.com/oss/release/grafana-5.4.3.linux-amd64.tar.gz
    dest: "{{ dl }}"
    remote_src: yes

#- name: Service creation for Grafana
#  command: mv /opt/graf* "{{ grafana }}"
#  template:
#    src: "{{ grafana-service }}"
#    dest: "{{ grafana-service-dest }}"
  
#- name: Configuration changes for Grafana
#  template:
#    src: "{{ grafana-service }}"
#    dest: "{{ grafana-service-dest }}"
#  notify: enable grafana

- name: Download and extract Prometheus to /opt
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.7.1/prometheus-2.7.1.linux-amd64.tar.gz
    dest: "{{ dl }}"
    remote_src: yes
    
#- name: Service creation for Prometheus
#  command: mv /opt/prom "{{ prometheus }}"
#  template:
#    src: "{{ prometheus-service }}"
#    dest: "{{ prometheus-service-dest }}" 
#  notify: enable prometheus  

- name: Download and extract Node-Eporter to /opt
  unarchive:
    src: "{{ node-exporter-dl }}"
    dest: "{{ dl }}"
    remote_src: yes

#- name: Service creation for Node-Exporter
#  command: mv /opt/node* "{{ node-exporter }}"
#  template:
#    src: "{{ node-exporter-service }}"
#    dest: "{{ node-exporter-dest }}"
#  notify: enable node-exporter

- name: https://www.haproxy.org/download/1.9/src/haproxy-1.9.4.tar.gz
  unarchive:
    src: "{{ haproxy-dl }}"
    dest: "{{ dl }}"
    remote_src: yes
    
#- name: Build HA-Proxy
#  command: 

    
#- name: Redirect HA-Proxy Port:80 to Grafana:443
  
#- name: Service creation for HA-Proxy
#  command: mv /opt/hapr* "{{ ha-proxy }}" 
#  template:
#    src: "{{ haproxy-service }}"
#    dest: "{{ haproxy-service-dest }}"
#  notify: enable haproxy