---
# handlers
- name: Enable and start SystemD service for Grafana
  systemd:
    daemon_reload: yes
    name: "{{ grafana.service }}"
    state: started
    enabled: yes
  listen: "enable grafana"

- name: Enable and start SystemD service for Prometheus
  systemd:
    daemon_reload: yes
    name: "{{ prometheus.service }}"
    state: started
    enabled: yes
   listen:  "enable prometheus"

- name: Enable and start SystemD service for Node Exporter
  systemd:
    daemon_reload: yes
    name: "{{ node-exporter.service }}"
    state: started
    enabled: yes
  listen: "enable node-exporter"
  
- name: Enable and start SystemD service for HA-Proxy
  systemd:
    daemon_reload: yes
    name: "{{ haproxy.service }}"
    state: started
    enabled: yes
  listen: "enable haproxy"
