---
- name: Enable and start SystemD service for Grafana
  systemd:
    daemon_reload: yes
    name: "{{ grafana_service_name }}"
    state: restarted
    enabled: yes
  listen: "enable and start Grafana"

- name: Enable and start SystemD service for Node Exporter
  systemd:
    daemon_reload: yes
    name: "{{ node_exporter_service_name }}"
    state: restarted
    enabled: yes
  listen: "enable and start node-exporter"
  
- name: Enable and start SystemD service for HA-Proxy
  systemd:
    daemon_reload: yes
    name: "{{ haproxy_service_name }}"
    state: restarted
    enabled: yes
  listen: "enable and start haproxy"
